name: Verify pull request
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        name: Run eslint/prettier and unit-tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.15
            - name: Install deps
              run: yarn install --frozen-lockfile
            - name: Build project
              run: yarn build
            - name: Launch linter
              run: yarn lint

            # - name: Check code coverage
            #   env:
            #       CODE_COVERAGE_PERCENT: 75
            #   run: |
            #       yarn test:coverage
            #       echo -e "Expected code coverage: "$CODE_COVERAGE_PERCENT
            #       npx lcov-total coverage/lcov.info --gte=$CODE_COVERAGE_PERCENT

            #       result=$?
            #       if [ "$result" != "0" ]; then
            #           echo -e "Code coverage degradation\n"
            #           exit 1
            #       fi
